plugins {
    id 'application'
}

repositories {
    mavenCentral()
    ivy {
        url = 'https://github.com/'
        patternLayout {
            artifact '/[organisation]/[module]/releases/download/[revision]/dependencies.jar'
        }
        metadataSources { artifact() }
    }
}

dependencies {
    implementation 'Anuken:Mindustry:v159.7'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'dev.airi.mindustry.tools.GameDataGenerator'
}
